### PR TITLE
Create Github Actions file to test builds before merging

### PR DESCRIPTION
**Pull request by KHVBui**

### CODE REVIEW

**Review by minhngo3818 — COMMENTED** [review]
Git action needs configuring eslint and prettier in test build in order to pass. Please add windows and mac to run test.

**Comment by KHVBui** [comment]
Going to need a Lint fix PR before merging this PR

**Comment by KHVBui** [comment]
PHEW I finally got the workflow to work. There was this fun bug where it didn't work on the windows build since windows uses a different eol character, but adding a gitattributes file to do eol normalization fixed it

**Comment by minhngo3818** [comment]
Sweet! Once this PR merged, we're going use this workflow to check every PRs.

**Comment by KHVBui** [comment]
Can you make the accepting review to merge? xD

**Review by minhngo3818 — APPROVED** [review]

**Pull request merged**
