### PR TITLE
Siddhant jain frontend restyle resources tab bar

### PR DESCRIPTION
**Pull request by codebysid**
Issue Number #131 
First Commit (Resources Tab Bar Restyled):- All the mentioned changes are made here.
Second Commit (Fixed Typo):- A typo was removed.

### CODE REVIEW

**Comment by minhngo3818** [comment]
Please use `npm run lint` to check errors and warnings. Then format the code by `npm run format:fix`

**Comment by codebysid** [comment]
thanks, both the scripts are executed successfully

**Review by minhngo3818 — APPROVED** [review]
Good jobs! The UI is ok right now. A follow-up tailwind conversion task will address more issues to rework.

**Comment by codebysid** [comment]
Sure , looking forward for more issues and code

**Pull request merged**
