### PR TITLE
fixed styling on Event Dates

### LINKED ISSUE #96: Bug: Dates on Events are too large for their boxes
Starting to implement Tailwind with app.css has broken elements that utilize the `<p>` tag. Tailwind overrides default margins that the styling for numerical dates or details used in the past.

Screen Shot 2022-10-07 at 11 13 57 AM
Screen Shot 2022-10-07 at 11 19 59 AM

### PR DESCRIPTION
**Pull request by fugarino**
Fixed event dates styling, this commit will close #96

### CODE REVIEW

**Review by KHVBui — APPROVED** [review]

**Comment by KHVBui** [comment]
Images of the fix for reference.
Before:
Screen Shot 2022-11-01 at 4 43 22 PM
After:
Screen Shot 2022-11-01 at 4 42 51 PM

**Comment by KHVBui** [comment]
@fugarino I'll leave resolving the conflicts and merging to you.

**Comment by minhngo3818** [comment]
Please resolve conflicts

**Review by minhngo3818 — APPROVED** [review]

**Comment by minhngo3818** [comment]
The PR has not resolved conflicts. CSS Styling will be no longer applicable

**Pull request closed without merging**
